Repository aui-framework/aui, pull requests merged in 2025-09, with the labels that each got.

#603 AUI define use CCache variable for AUI builds
  CMakeLists.txt
  aui.boot.cmake
Labels: performance, cmake

#602 MkDocs: Gather usages of class/macros/function
  docs/python/generators/doxygen.py
  docs/python/generators/examples_helpers.py
  docs/python/generators/examples_page.py
  docs/python/generators/macros_page.py
Labels: documentation

#618 Created buttons in README
  README.md
Labels: documentation

#619 Added dark theme for star history
  README.md
Labels: documentation

#613 Improved interface of OpenGL wrapper
  .gitignore
  aui.toolbox/src/ShadingLanguage/Lang/Frontend/GLSLFrontend.cpp
  aui.toolbox/src/ShadingLanguage/Lang/Frontend/GLSLFrontend.h
  aui.views/src/AUI/GL/OpenGLRenderer.cpp
  aui.views/src/AUI/GL/Program.cpp
  aui.views/src/AUI/GL/Program.h
  examples/app/fractal/src/FractalView.cpp
  examples/app/fractal/src/FractalView.h
Labels: design
